spring:
  application:
    name: aggregator
  config:
    import: configserver:http://localhost:8080
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000